using System;
using System.Collections.Generic;

namespace Roche_Scoreboard.Services;

/// <summary>
/// Provides an in-app changelog shown on the sport selection screen.
/// Add a one-liner per change to the current version's entry.
/// </summary>
internal static class ChangelogService
{
    public static IReadOnlyList<ChangelogVersion> Versions { get; } =
    [
        new("2.7.1", "2026-04-30",
        [
            "[Fixed] Recent Scores overlay no longer overflows at small scorebug sizes (~400×200) — width floor reduced from 320px to 110px so the overlay scales down with the actual score column instead of forcing the panels off-screen",
            "[Fixed] Recent Scores overlay now fully hides the team name, goal count and behind count panels while it is on-screen — those cells fade to zero opacity so only the Total score panels and team logo panel remain visible behind the overlay (previously leftover digits and name letters could peek through)",
            "[Improved] Recent Scores rows now stretch to fill the overlay width with equal-sized GOAL and BEHIND boxes (single 28pt label) and tighter padding/margins so all 5 entries fit cleanly at small sizes",
            "[Improved] Recent Scores header height reduced from 34px to 22px with a smaller 14pt label inside a downscaling Viewbox so the header strip stays proportional on tiny scorebugs",
            "[Improved] Scores This Quarter overlay simplified to a boxes-only layout — visible team-name headers removed and the Q1/Q2/Q3/Q4 score boxes now scale up via a Both-direction Viewbox to fill the freed space",
            "[Improved] Lead Changes overlay content wrapped in a downscaling Viewbox so the bar text fits cleanly at ~400×200",
        ]),
        new("2.7.0", "2026-04-29",
        [
            "[New] TRAINING MODE \u2014 brand new third sport mode for stopwatches, drills and interval sessions; selectable from the top-right tile on the sport selection screen with its own amber-glow neon styling matching the AFL/Cricket card techniques",
            "[New] Training control panel \u2014 add multiple titled timers to a queue, drag rows directly to reorder (with a glowing blue insertion line) or use the Up/Down buttons, remove individually or Clear All, with live ACTIVE card showing remaining time at 84pt and a session-total readout that ticks down across the whole queue",
            "[New] Training transport \u2014 Start / Pause toggle, Reset active interval, Skip to next, plus quick \u002B1:00 / \u002B0:10 buttons that now correctly extend the running timer on the fly without disturbing the queue (previously only worked while paused)",
            "[New] Training quick presets \u2014 one-click WARM-UP 5:00, DRILL 3:00, REST 1:00, SPRINT 0:30, MATCH PLAY 10:00, COOL DOWN 5:00 to drop common intervals straight into the queue",
            "[New] Interval session builder \u2014 enter Rounds / Work / Rest seconds and one click expands the queue into a Tabata-style WORK \u2194 REST sequence (e.g. 8 rounds \u00d7 20s work / 10s rest)",
            "[New] Training scorebug \u2014 huge centred countdown (420pt source font, scales down via Viewbox) with the title above in a neon-bordered chip and a live progress bar that fills as the timer winds down; status pill shifts blue \u2192 green \u2192 amber \u2192 red as the state changes",
            "[New] LAST 10s pulse \u2014 the timer drop-shadow glow pulses once per second across the final 10 seconds so the operator and athletes can see the wind-down at a glance",
            "[New] Whole-screen finish flash \u2014 when an interval hits zero the entire scorebug strobes red\u002Fblack at 420ms cadence so a finish is unmistakable from any distance, with a FINISHED status pill on the active card",
            "[New] UP NEXT bar \u2014 the bottom of the scorebug slides up a strip showing the next timer\u0027s title and duration whenever a queued timer exists; collapses smoothly when the queue is exhausted, and never overlaps the timer thanks to a flexible spacer-row layout that always keeps the centre block centred in the available space",
            "[New] NOW STARTING preview \u2014 during the finish flash a green-accented bar at the bottom shows the next timer already ticking down live in the background, so the operator sees the new clock running before the swap",
            "[New] Smooth interval transitions \u2014 finished timer holds for ~7.5s while the next interval pre-stages live at the bottom; transition uses a clean in-place crossfade (450ms) instead of a vertical slide, with the new active timer fading in pre-populated with the next clock\u0027s live values",
            "[New] Session complete overlay \u2014 once the queue is exhausted, a full-screen SESSION COMPLETE banner fades in over a 10-second extended red\u002Fblack strobe, then everything fades back out to the ready state",
            "[New] Auto-advance \u2014 the next queued timer auto-starts the moment the transition finishes, so a multi-interval session runs hands-free end-to-end",
            "[New] Operator console UX \u2014 Training control panel redesigned with a top status bar (brand chip, live SESSION TOTAL, prominent Exit), a NOW PLAYING readout at 42pt title \u002F 84pt clock with a status pill, an oversized START button (20pt) for the primary action, and grouped builder cards (Add Timer \u002F Quick Presets \u002F Interval Builder) with coloured accent strips and helper text on each",
            "[New] Operator keyboard shortcuts \u2014 Space toggles Start\u002FPause, S skips, R resets the active timer, Esc exits Training Mode; Enter while typing the title or any numeric field adds the timer; numeric inputs reject non-digit keystrokes; on-screen shortcut reference card included",
            "[New] Drag-to-reorder queue \u2014 grab any queue row and drag to move it; a glowing 3px blue insertion line floats above the rows showing exactly where it will land; the source row dims while dragging; releasing fires a single MoveTimer with no per-row re-animation cascade so the rebuild is glitch-free",
            "[Improved] Custom button template \u2014 every Training-mode action button now uses a custom ControlTemplate that respects Background\u002FForeground\u002FBorderBrush, so the saturated button colours actually paint instead of being hidden behind the system Aero grey-white chrome (text was reading as light-on-light before)",
            "[Improved] Resizable control panels \u2014 every sport mode\u0027s control panel (AFL, Cricket, Training) is now wrapped in a downscaling Viewbox so it scales down proportionally when the host window is smaller than its design size, and the main window MinWidth\u002FMinHeight have been dropped (860\u00d7580 \u2192 420\u00d7320) so the app can be operated on small laptops or low-res screens with every control still visible and clickable",
            "[Improved] Sport selection screen entry animation now also fades and drops the new TRAINING MODE tile in from above, with hover scale and glow ramp matching the AFL\u002FCricket card hover treatment",
            "[New] Robust crash- and shutdown-safe save \u2014 the live game state (including the running stopwatch) is now flushed every 5 seconds while the clock is running, on every clock pause, on Windows session-end (logoff\u002Fshutdown\u002Frestart) and on a terminating unhandled exception, so a crash, force-kill, power loss or session-end never loses more than a few seconds of clock progress",
            "[Fixed] On a clean close mid-quarter, the saved-game ElapsedInQuarter no longer lags behind the live stopwatch \u2014 the auto-save and crash-path saves all read the live MatchManager.ToState() so the persisted clock matches the on-screen clock to within the auto-save interval",
            "[New] Crash-handler save uses Dispatcher.Invoke to marshal onto the UI thread, so a save attempt during a background-thread crash is still safe and completes before process termination",
            "[Improved] Scoring Run overlay layout \u2014 the run value (e.g. 20-0), SCORING RUN label and elapsed time now sit on a single horizontal line, with the value bumped to 84pt, label to 48pt and elapsed time to 44pt for high-impact broadcast readability",
            "[Improved] Scoring Run overlay colour contrast \u2014 all three text elements now run through ContrastHelper.GetReadableTextColor against the actual gradient mid-point so the overlay reads cleanly against any team primary colour (yellow, lime and cyan no longer collapse into the team-tinted background)",
            "[Improved] Scoring Run elapsed time gets bright pure-white treatment with a soft black drop-shadow instead of the previous muted grey, so the live counter is unmistakably legible at distance",
        ]),
        new("2.6.3", "2026-04-27",
        [
            "[New] Pause-aware match clock \u2014 scoring run, scoreless and team-drought elapsed timers now freeze the instant the game clock is paused and resume from where they left off when it restarts, so 'TIME SINCE LAST SCORE' and scoring-run elapsed track real game time instead of wall-clock time across pauses, breaks, save/restore and app restarts",
            "[New] Drought / scoreless milestone detection (e.g. 'scoreless every 4 min from 8:00') is now match-clock-driven so a milestone only fires after that many minutes of actual game time, not wall-clock time",
            "[New] Recent Scores overlay redesigned for clarity \u2014 stripped of time stamps, running scores and score-type icons; each row is now a sharp neon team-coloured rectangle with the team's primary colour as both the border AND the glow, so every panel is unmistakably team-dedicated",
            "[New] Recent Scores score-type label (GOAL / BEHIND) now renders in the team's primary colour reinforcing team identity; goals and behinds share the same neon styling so the row chrome doesn't compete with the score-type text",
            "[New] Quarter Scores overlay caption replaced with a single-line, readable 'SCORES THIS QUARTER' centre chip; team scores pushed to the outer left and right edges of the bar with the centre caption sitting cleanly between them",
            "[Improved] Bottom score bar enlarged across every break/rotation screen \u2014 logos 48 \u2192 60px, team abbreviation source font 32 \u2192 40pt (Viewbox cap 38 \u2192 50), G/B chip digits 28 \u2192 34pt, total score source font 44 \u2192 56pt, centre quarter/timer 18\u002F11 \u2192 22\u002F14pt for vastly better long-distance readability",
            "[Improved] Break / Score Worm / Stats team-name boxes unified into a single 220 \u00d7 44 single-line strip across all three rotation screens \u2014 same dimensions, same logo placement, same 28pt source font; long names auto-shrink via Viewbox to fit one line in the wider 220px column instead of being cropped or wrapped",
            "[Improved] Bottom-bar host row enlarged from 80 \u2192 100px on every rotation screen (Quarter Summary, Score Worm, Stats, Weather) so the bigger score-bar content has clean breathing space and the bar reads identically as the rotation cycles through",
        ]),
        new("2.6.2", "2026-04-26",
        [
            "[New] Update Available alert fully redesigned in scoreboard style \u2014 sharp edges, neon double-border, glowing icon badge, side-by-side INSTALLED/LATEST version chips with team-style accents, sectioned WHAT'S NEW panel, neon outline buttons and a glowing progress bar",
            "[New] Game In Progress alert is now genuinely team-dedicated \u2014 split home/away gradient stripe across the top, team-coloured borders + glows on each team block, full match readout (big totals, G.B line, quarter, elapsed clock, margin) reconstructed from the saved snapshot, all colours pulled from the saved game state",
            "[Improved] Quarter Summary screen polish pass \u2014 team-name boxes lengthened, all score cells get more breathing room, all four Q-label cells render at identical size (no more uneven Q1/Q2/Q3/Q4 widths)",
            "[Improved] Stats screen visual consistency \u2014 all four stat bars now identical height, side value text bumped to 40pt with wider 100px columns, team-name boxes wrapped in a Viewbox so the full team name fills the header at 24pt",
            "[Improved] Bottom score bar redesigned with broadcast-style team-coloured G/B chips \u2014 rounded outline borders, team-coloured tinted backgrounds, glowing goals chip, larger digits (28pt) and G/B suffix labels",
            "[Improved] Score bar abbreviation slot bumped to 32pt source font with a 38px Viewbox cap so team abbreviations read clearly across every screen",
            "[Improved] Break-screen bottom bar height raised to 96px (from the standard 80px) so the Quarter Summary bar is more prominent without clipping at smaller window sizes \u2014 every other screen keeps the standard 80px bar",
            "[Improved] Full team names (instead of abbreviations) now render in the dedicated team-name boxes on the Stats, Score Worm and Quarter Summary screens; long names auto-shrink via Viewbox caps so they always fit",
            "[Fixed] Score Worm graph now redraws when the host control resizes \u2014 the worm adapts to new window dimensions instead of staying on stale pixel coordinates from the first Populate",
            "[Fixed] Weather screen condition text (e.g. 'Mostly Cloudy with Showers') wraps to a second line instead of being clipped by the card width",
        ]),
        new("2.6.1", "2026-04-25",
        [
            "[New] Tiered scoring-run detection \u2014 four parallel tiers (Burst, Standard, Sustained, Mega) with their own thresholds so runs of every shape qualify: tight 2-goal flurries, classic 18-1 stretches, long 30+ point quarter-spanning runs, and overwhelming 48+ point dominance",
            "[Improved] Scoring-run decision making \u2014 picks the run with current momentum (tier \u2192 freshness \u2192 ratio) instead of raw net dominance, so a fresh 12-0 burst beats a stale 30-9 run from earlier",
            "[Improved] Scoring-run cooldown is now match-clock-based, allows tier escalation to override the same-team cooldown, and uses a much shorter cross-team cooldown so momentum flips land close to when they happen",
            "[Improved] Recent-tail guard tightened to a 4-minute match-clock window (independent of the scan window) so a sustained run has to still be hot right now, not just hot historically",
            "[Improved] Single-event \u201Cruns\u201D and sub-goal growth re-shows are now correctly rejected",
            "[Improved] All presentation screens (stats, weather, score worm, intro, break, cricket scorebug, cricket summary, presentation score bar) now adapt to any window dimensions without distortion \u2014 things shift around the screen instead of stretching or condensing",
        ]),
        new("2.6.0", "2026-04-25",
        [
            "[Improved] Scoring run detection now uses the match clock instead of the wall clock \u2014 runs that span multiple quarters, paused matches, saved-game restores, app restarts and crashes are now correctly identified (e.g. a 35-8 run from Q1 02:00 to Q2 04:00 is detected even after closing and reopening the app)",
            "[Improved] Scoring runs land within ~3 seconds of the triggering goal instead of being delayed up to 3 minutes by the informational-overlay cooldown",
            "[New] Event-driven overlays (scoring runs, lead changes, droughts, scoreless) now take priority over scheduled overlays \u2014 if a scheduled overlay is on-screen when an event-driven moment fires, it fades smoothly so the time-sensitive overlay can show immediately",
            "[New] All 7 scheduled overlays (stats, win prob, quarter scores, last 5 scores, weather, forecast, rain) now have equal chance of appearing and rotate evenly \u2014 uniform interval, uniform priority, and a small randomisation jitter for tied candidates so no overlay is structurally favoured",
            "[New] Narrow-mode responsive layout \u2014 when the scorebug width drops past a threshold, the left clock column collapses and the bottom bar swaps from the scrolling marquee to a full-width quarter+clock readout so the timer stays visible and readable",
            "[New] Start/Pause button shows the next quarter dynamically between quarters \u2014 \u0022\u25B6 Start Q2\u0022, \u0022\u25B6 Start Q3\u0022, \u0022\u25B6 Start Q4\u0022 \u2014 instead of a generic \u0022Start\u0022",
        ]),
        new("2.5.3", "2026-04-23",
        [
            "[Fixed] Stats overlay no longer fires within 5 seconds of resuming a saved game \u2014 the overlay scheduler now seeds a 100-second early-buffer marker on resume so the viewer gets a clean beat of scorebug-only after pressing Resume",
            "[Fixed] Weather icons now render in full colour across the scorebug overlays and weather screen \u2014 forced Segoe UI Emoji on every icon TextBlock so WPF picks the COLR/CPAL coloured glyphs instead of falling back to monochrome",
            "[Fixed] Scoring run with zero opposition points (18-0, 20-0, 30-0 etc.) no longer absorbs an unrelated earlier opposition score \u2014 a clean-run guard breaks the backward scan and extension pass the moment opposition history is encountered, so a true 18-0 displays as 18-0 not 18-6",
        ]),
        new("2.5.2", "2026-04-23",
        [
            "[Fixed] Critical random crash during matches \u2014 win probability Monte Carlo was iterating the live event list on worker threads while the UI added score events, causing an InvalidOperationException that tore the process down",
            "[Fixed] Win probability engine now snapshots the event list to an immutable array before background simulation, eliminating the cross-thread mutation crash",
            "[New] Global exception handlers installed \u2014 Dispatcher, AppDomain and TaskScheduler unhandled exceptions are now logged to %LOCALAPPDATA%\\Roche_Scoreboard\\crash.log and survivable ones are swallowed instead of terminating the app mid-match",
            "[Improved] Win probability engine significantly smarter \u2014 scoring-shot intensity (rewards attacking pressure even with inaccurate kicking), recency-weighted events via 12-min exponential decay, pressure regime (field-position battle), in-front inertia, comeback drive, clutch late-game regime and Q4 fatigue modelling",
            "[Improved] Solid 90-second cooldown between the end of one overlay and the start of the next \u2014 applies to queued, event-driven and informational overlays",
            "[Improved] Scoreless and team-drought overlays fade out smoothly the instant a goal is scored so stale \u0022time since last score\u0022 info doesn\u0027t linger after scoring resumes",
            "[Improved] Lead-changes overlay now suppresses automatically when the current margin is more than 4 goals \u2014 stops showing \u00225 lead changes!\u0022 at 30-point blowouts",
        ]),
        new("2.5.1", "2026-04-23",
        [
            "[Improved] Recent Scores panel now auto-shrinks text when 6+ rows are displayed (5 scores + quarter-split header) so content never clips inside the cells",
            "[Improved] Scoring run detection smarter \u2014 added recent-tail guard (last 4 events must be \u226570% dominated by the run team) so cooled-off runs like 18-1 \u2192 18-7 no longer trigger the overlay",
            "[Improved] Scoring run backward scan now stops on two consecutive opponent scores at the tail, preventing random earlier opposition goals from being absorbed into totals (e.g. a 20-2 run no longer inflates to 20-8)",
            "[Improved] Scoring run dominance threshold tightened from 2.5\u00d7 to 2.9\u00d7 so borderline cases like 18-7 (2.57\u00d7) and 20-8 (2.5\u00d7) are rejected, while 38-13 (2.92\u00d7) still qualifies",
            "[Improved] Scoring run opponent cap reduced from 25 to 18 points so the opponent can never be as dominant as the run team within the window",
            "[Improved] Weather forecast, weather stats and rain forecast overlay heights raised from 110px to 130px so large text no longer clips",
            "[Improved] +6 and +1 goal swipe text enlarged from 56pt to 80pt for much higher visibility when a score lands",
            "[Improved] Recent Scores panel text bumped in roomy mode \u2014 header 26pt, GOAL/BEHIND 26pt, score type icon 28pt, team badge 26pt with wider padding, time 18pt, running score 22pt",
        ]),
        new("2.5.0", "2026-04-23",
        [
            "[New] Scores-This-Quarter overlay fully redesigned \u2014 sharp neon boxes, team-coloured borders on every cell, Total boxes with team-coloured drop-shadow glow, separate GOALS and BEHINDS boxes, centre QTR chip with cyan border and glow",
            "[New] Scoring run detection now has a two-phase scan \u2014 strong runs (\u226518 pts, dominance \u22652.5\u00d7) keep absorbing earlier contiguous events past the 30-min window so long dominant runs show their true length",
            "[New] Recent Scores side panel text sizes overhauled \u2014 header 20pt, team badge 20pt with wider padding, GOAL/BEHIND text 20pt, score type icon 22pt, running score 17pt bright white, time text 15pt",
            "[New] Weather forecast, weather stats and rain forecast overlays redesigned with much larger text \u2014 forecast times/temps 20/30pt, rain % 26pt, wx stats labels 18pt and values 46pt",
            "[New] Scoring run overlay restructured \u2014 huge 72pt score on the left, tight stacked 36pt label + 24pt detail on the right, eliminates negative space",
            "[Improved] Overlays now allowed to show while the countdown timer is paused (break-screen suppression still applies)",
            "[Improved] Solid 2.5-second cooldown between consecutive queued overlays so each one gets a clear beat of scorebug-only time",
            "[Improved] Smooth animated exit when an overlay is cancelled by the next one or by the end of a quarter \u2014 no more hard-snap transitions",
            "[Improved] Scoring run thresholds broadened \u2014 dominance ratio 3.0\u2192 2.5\u00d7, opponent cap 12\u2192 25 pts so runs like 36-12, 38-13 and 50-20 now register",
            "[Improved] Scoring run cross-quarter gap widened to 20 min wall-clock so runs spanning a quarter break (e.g. Q1 28\u2032 \u2192 Q2 7\u2032) are no longer truncated",
            "[Improved] Scoring run concentration window widened to 30 min, redundancy escape now has three paths (concentrated burst, strong dominance \u22654\u00d7, large absolute run \u226530pts)",
            "[Improved] Scoreless overlay first milestone 8min \u2192 10min (repeats every 5 min)",
            "[Improved] Scoreless and drought overlays now mutually exclusive \u2014 if the game is fully scoreless, only the scoreless overlay shows (not both)",
            "[Fixed] Drought overlay double-firing \u2014 milestone now consumed atomically when detected so rapid clock ticks can't enqueue the same drought multiple times",
            "[Fixed] Scoring run overlay not triggered for runs spanning Q1 28\u2032 into Q2 7\u2032 due to too-tight cross-quarter gap limit",
        ]),
        new("2.4.0", "2025-07-19",
        [
            "[Improved] Scoring run detection now scans both teams and picks the stronger run, not just the last scorer",
            "[Improved] Scoring run detection broadened — 30-event / 30-minute lookback window captures longer game-spanning runs",
            "[Improved] Scoring run spans quarter breaks (up to 5 min gap) so cross-quarter momentum isn't lost",
            "[Improved] Overlay scheduling overhauled — all 7 overlays (stats, win prob, quarter scores, last 5 scores, forecast, weather, rain) now rotate evenly",
            "[Improved] Weather and rain overlay priority boosted so they actually appear during matches",
            "[Improved] Overlay minimum intervals reduced (3–5 min) and target overlays per quarter doubled for better rotation",
            "[Improved] All overlay display durations increased (12–16 seconds) for easier reading",
            "[Improved] Break screen slideshow interval increased from 10s to 18s per screen",
            "[Improved] Scoreless and team drought overlays now trigger at 10 minutes then every 5 minutes",
            "[Improved] All percentages in stats overlay and stats screen now display as whole numbers (no decimals)",
            "[Improved] Last 5 scores overlay text contrast improved — team badge text auto-adapts to light/dark team colours",
            "[Improved] Last 5 scores time and score text brightened for better readability on dark background",
            "[Improved] Break screen titles standardised — consistent font size, weight, and family across all screens",
            "[Improved] Weather icons diversified with more distinct and colourful emoji for each condition",
        ]),
        new("2.3.0", "2025-07-18",
        [
            "[New] Game state persistence — in-progress matches are auto-saved and can be restored if the app is closed mid-game",
            "[New] Recent Scores overlay — shows last 5 scores with quarter splits, team-coloured borders, and goal/behind icons",
            "[New] RecentScores added to the overlay scheduling rotation system",
            "[New] Custom styled resume game dialog replaces system MessageBox, shown after app loads",
            "[New] Score event time editing — adjust the game time of any score from the match log editor",
            "[Improved] Recent Scores items styled with team primary/secondary colour borders, left accent strip, and glow effects",
            "[Improved] Smooth animated transitions for overlay expand/collapse — columns, name strips, and G/B panels fade in/out together",
            "[Improved] Total score text size stays consistent during Recent Scores overlay",
            "[Improved] Update and resume-game alerts now show sequentially after the app window is visible, with update taking priority",
        ]),
        new("2.2.1", "2025-07-17",
        [
            "[Improved] All overlay bars redesigned with bold 2px coloured borders, #0D1117 backgrounds, and vibrant team-coloured text with glow effects",
            "[Improved] Score worm full-screen redesigned to match neo design language with team-tinted backgrounds and bold borders",
            "[Improved] Bottom score bar on break screens redesigned with team-colour section borders, gold quarter label, cyan timer, and glow effects",
            "[Improved] Stats bar corners now sharp (no rounding) to match neo design",
            "[Improved] Team logos now auto-trimmed to remove transparent padding for tighter circle fit",
            "[Improved] App title now shows version number (e.g. Roche Scoreboard v2.2.1) across all windows and taskbar"
        ]),
        new("2.2.0", "2025-07-16",
        [
            "[Improved] Bold 2px coloured borders on every card, cell, and header across all presentation screens",
            "[Improved] Subtle dark backgrounds (#0D1117) behind borders for high-contrast neo aesthetic",
            "[Improved] All text now uses vibrant, meaningful colours — gold titles, cyan clocks, team-coloured values",
            "[Improved] Team headers redesigned: subtle dark bg with bold team-colour borders instead of solid fill",
            "[Improved] Quarter labels now cyan-bordered with vibrant cyan text instead of grey",
            "[Improved] Weather card dividers tinted to match card theme (amber/green) instead of neutral grey",
            "[Improved] Score cell borders now full-opacity team primary colour at 2px thickness",
            "[Improved] Stat bar borders now full-opacity blended team colour at 2px thickness"
        ]),
        new("2.1.3", "2025-07-15",
        [
            "[New] Scores This Quarter overlay shows quarter scoring breakdown in stats-bar style",
            "[New] QTR SCORES manual overlay button added to Game Analysis panel",
            "[Fixed] Stats bar corner radius now correctly rounded on outer edges only",
            "[Fixed] Scoring run detection now recognises dominant runs over longer periods (e.g. 20-0 in 10 minutes)",
            "[Improved] Drought overlay text colour now adjusts for contrast against darkened team background"
        ]),
        new("2.1.2", "2025-07-14",
        [
            "[Improved] Match log team name text now adjusts for contrast against dark background",
            "[Improved] Scoreless and team drought overlays now trigger at 8 minutes then every 4 minutes",
            "[Improved] Drought overlay text changed to 'TIME SINCE LAST {TEAM} SCORE'",
            "[New] Continue quarter button allows resuming a quarter after accidentally ending it",
            "[New] Live clock adjustment buttons (±1s, ±10s) and set time fields",
            "[Fixed] Auto-updater now correctly downloads .exe release assets instead of source code",
            "[Fixed] Home team logo no longer pulses on score or button presses"
        ]),
        new("2.1.0", "2025-07-13",
        [
            "[Improved] Scoring buttons now show keyboard shortcut hints (Ctrl+G/B, Alt+G/B)",
            "[Improved] Match result text now says 'defeated by' at full time instead of 'leads by'",
            "[Improved] Header margin indicator is now tinted with the leading team's colour",
            "[Improved] Last event text in the header now shows actual team names instead of generic Home/Away",
            "[Improved] Undo button now visually dims when no events exist to undo",
            "[Improved] Clipboard copy buttons now show brief 'Copied!' feedback",
            "[Improved] Scoring panel colours now have a minimum brightness floor for very dark team colours",
            "[Improved] End Quarter button now asks for confirmation before ending Q4 (full time is irreversible)",
            "[Improved] Web state broadcast now includes event count, last event, and match result",
            "[Fixed] Start/Pause and Full Time button brushes are now cached — eliminates per-frame allocations",
            "[Fixed] Quarter snapshot array now uses proper nullable typing instead of null! suppression",
            "[Fixed] Eye dropper preview now reuses a single brush instead of allocating one per mouse move",
            "[Fixed] ContrastHelper.GetReadableTextBrush now returns a frozen brush — prevents cross-thread issues",
            "[Fixed] WeatherService catch clauses narrowed from bare catch to specific exception types",
            "[Changed] QuarterSnapshot converted to a record for value equality and reduced boilerplate",
            "[Changed] EndQuarter clock-stop logic simplified — removed duplicated stopwatch reset",
            "[Changed] Modernised collection initialisers to use C# 12 collection expressions across models",
            "[Improved] Scorebug window now adapts layout and element sizes responsively on resize instead of uniformly stretching"
        ]),
        new("2.0.2", "2025-07-12",
        [
            "[Fixed] App could become unlaunchable after dismissing an update prompt on close",
            "[Fixed] Hardened startup update check so network or parse failures never block launch"
        ]),
        new("2.0.1", "2025-07-11",
        [
            "[New] Match log panels expand on hover to reveal edit controls",
            "[Changed] Redesigned match strip header with cinematic gradient and broadcast typography",
            "[Changed] Redesigned tab bar as full-width broadcast channel selectors",
            "[Changed] Changelog now centred at bottom of sport selection screen with hover expand"
        ]),
        new("2.0.0", "2025-07-11",
        [
            "Added auto-updater — checks GitHub for new releases on launch and close",
            "Added in-app changelog on the sport selection screen",
            "Redesigned control panel navigation — clean text signpost tabs with accent underline",
            "Redesigned match strip — thin integrated bar with compact layout"
        ]),
        new("1.0.0", "2025-06-20",
        [
            "AFL scoreboard with live scorebug, summary, and stats screens",
            "Cricket support with full scorebug and match management",
            "Live weather overlays with forecast, temperature, and rain data",
            "Custom goal video animations per team",
            "Web remote control and live view with QR codes",
            "Automatic stat overlays, scoring run detection, and lead change alerts",
            "Win probability engine with live overlay",
            "Team logo crop and positioning controls",
            "Ticker message system with scrolling bottom bar",
            "Initial release of Roche Scoreboard"
        ])
    ];
}

/// <summary>
/// A single version entry in the changelog.
/// </summary>
internal sealed record ChangelogVersion(string Version, string Date, IReadOnlyList<string> Changes);
